trigger:
  - master

pool:
  vmImage: ubuntu-latest


stages :
  - stage: install terraform
    jobs:
      - job: install
        continueOnError: false
        steps:
          - task: TerraformInstaller
              displayName: install terraform
              inputs:
                terraformVersion: latest

  - stage: terraform init
    jobs:
      - job: init
        steps:
          - task: TerraformCLI
              displayName: 'terraform init'
              inputs:
                command: init
                backendType: azurerm
                backendServiceArm: 'eteo-akademia-devops_test-dev'
                ensureBackend: true
                backendAzureRmResourceGroupName: 'Akademia1'
                backendAzureRmResourceGroupLocation: 'West Europe'
                backendAzureRmStorageAccountName: 'jancsostorage02'
                backendAzureRmContainerName: 'content'
                backendAzureRmKey: terraform.tfstate

          - task: TerraformCLI
              displayName: 'terraform apply'
              inputs:
                command: apply -var="textlength=10"
                environmentServiceName: 'eteo-akademia-devops_test-dev'