trigger:
  - master

pool:
  vmImage: ubuntu-latest


stages :
  - stage: validate
    jobs:
      - job: validate
        continueOnError: false
        steps:
          - task: TerraformInstaller@0
            displayName: 'install'
            inputs:
              terraformVersion: '1.0.0'
          - task: TerraformTaskV1@0
            displayName: 'init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'eteo-akademia-devops_test-dev'
              backendAzureRmResourceGroupName: 'Akademia1'
              backendAzureRmStorageAccountName: 'jancsostoragedevops'
              backendAzureRmContainerName: 'content'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTaskV1@0
            displayName: 'validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'

  - stage: plan
    dependsOn: [validate]
    condition: succeeded('validate')
    jobs:
      - job: terraform_plan_develop
        steps:
          - checkout: self
          - task: TerraformInstaller@0
            displayName: 'install'
            inputs:
              terraformVersion: '1.0.0'
          - task: TerraformTaskV1@0
            displayName: 'init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'eteo-akademia-devops_test-dev'
              backendAzureRmResourceGroupName: 'Akademia1'
              backendAzureRmStorageAccountName: 'jancsostoragedevops'
              backendAzureRmContainerName: 'content'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTaskV1@0
            displayName: 'plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              commandOptions: '-var="textlength=13"'
              environmentServiceNameAzureRM: 'eteo-akademia-devops_test-dev'
          - task: TerraformTaskV1@0
              displayName: 'apply'
              inputs:
                provider: 'azurerm'
                command: 'apply'
                commandOptions: '-auto-approve -var="textlength=13"'
                environmentServiceNameAzureRM: 'eteo-akademia-devops_test-dev'